"""
Frontend Application for Multi-Agent Research Assistant.

This Streamlit application provides a research interface where users input
a topic and receive a comprehensive research report generated by multiple
specialized AI agents working in sequence.
"""

import streamlit as st
import os
import sys

PACKAGE_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
if PACKAGE_ROOT not in sys.path:
    sys.path.insert(0, PACKAGE_ROOT)

from orchestrator import run_research_pipeline
from components import render_app_footer, run_with_status_updates


st.title("Multi-Agent Research Assistant")

st.markdown("""
This research assistant uses multiple AI agents to investigate your topic:
1. **Search Agent** - Collects raw information
2. **Summarizer Agent** - Condenses findings into key points
3. **Fact-Checker Agent** - Reviews for accuracy and bias
4. **Report Generator** - Produces the final research brief
""")

topic = st.text_input("Enter your research topic:", placeholder="e.g., AI trends in healthcare")

if st.button("Start Research") and topic:
    results = run_with_status_updates(
        lambda: run_research_pipeline(topic),
        start_message="Running the multi-agent research pipeline..."
    )

    st.success("Research complete!")

    st.subheader("Search Results")
    st.info(results["search"])

    st.subheader("Summary")
    st.write(results["summary"])

    st.subheader("Fact-Checker Feedback")
    st.warning(results["corrections"])

    st.subheader("Final Report")
    st.success(results["report"])


render_app_footer()
